### ISSUE TITLE
aws-allowed-parameters should apply for input parameters only

### ISSUE THREAD

**Issue by Ishino** [andylockran/spectral-aws-apigateway-ruleset#6]
For input parameters, only the following attributes are supported: name, in, required, type, description. Other attributes are ignored.

Input parameters are parameters defined for a form

```
    requestBody:
      content:
        application/x-www-form-urlencoded:
          schema:
            type: object
            properties:
              id:
                type: string
                format: uuid
              address:
                # complex types are stringified to support RFC 1866
                type: object
                properties: {}
```
or
```
    requestBody:
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              id:
                type: string
                format: uuid
              address:
                # default Content-Type for objects is `application/json`
                type: object
                properties: {}
              profileImage:
                # default Content-Type for string/binary is `application/octet-stream`
                type: string
                format: binary
              children:
                # default Content-Type for arrays is based on the `inner` type (text/plain here)
                type: array
                items:
                  type: string
              addresses:
                # default Content-Type for arrays is based on the `inner` type (object shown, so `application/json` in this example)
                type: array
                items:
                  type: '#/components/schemas/Address'
```
I believe the `aws-allowed-parameters` rule is overreaching by also applying this to path and query parameters.

https://swagger.io/specification/#request-body-object

**Comment by andylockran** [comment]
Heya @Ishino ,

I'd interpreted this rule from the following page:

https://swagger.io/docs/specification/describing-parameters/

In OpenAPI 3.0, parameters are defined in the parameters section of an operation or path. To describe a parameter, you specify its name, location (in), data type (defined by either schema or content) and other attributes, such as description or required. Here is an example: 
`paths:
      /users/{userId}:
        get:
          summary: Get a user by ID
          parameters:
            - in: path
              name: userId
              schema:
                type: integer
              required: true
              description: Numeric ID of the user to get`

So I've applied this rule to $.components.parameters.*

**Comment by andylockran** [comment]
In the important notes document, the following suggestion is made:

- For input parameters, only the following attributes are supported: name, in, required, type, description. Other attributes are ignored.

However, in the example in this document (and to enable params-only validation) - the attribute 'schema' is used.

https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-validation-sample-api-swagger.html

**Comment by andylockran** [comment]
Closing due as AWS API Gateway does not support schemas for path and query parameters.  It only checks for their presence, and whether they have content, and does not use the schema to validate.
