### ISSUE TITLE
Invalid jsonpath for aws-proxy?

### ISSUE THREAD

**Issue by ajoga** [andylockran/spectral-aws-apigateway-ruleset#63]
Hello,

I'm starting to use this ruleset (thanks!) and it seems this jsonpath is not legal (closing bracket, `]` not present), or am I missing something? 

https://github.com/andylockran/spectral-aws-apigateway-ruleset/blob/1a5c1cd1580cf708b43426465073ec7f18bce570/aws_important_notes.yml#L143

Thanks

**Comment by andylockran** [comment]
Thanks for spotting that - I need to clean up my tests to test individual rules - fix published in 2.0.2
